# version: '3.0'

services:
  producer_104_jobs:
    image: benitorhuang/crawler_jobs:0.0.2
    hostname: "crawler_104_jobs_producer"
    command: python -m crawler.project_104.producer_jobs_104
    environment:
      - TZ=Asia/Taipei
    networks:
      - my_network

  producer_104_category:
    image: benitorhuang/crawler_jobs:0.0.2
    hostname: "crawler_104_category_producer"
    command: python -m crawler.project_104.producer_category_104
    environment:
      - TZ=Asia/Taipei
    networks:
      - my_network

  producer_104_urls:
    image: benitorhuang/crawler_jobs:0.0.2
    hostname: "crawler_104_urls_producer"
    command: python -m crawler.project_104.producer_urls_104
    environment:
      - TZ=Asia/Taipei
    networks:
      - my_network

networks:
  my_network:
    external: true